name: instaclon
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.7
  uuid: ^3.0.7
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.2
  font_awesome_flutter: ^10.5.0
  flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  image: ^4.0.17
  flutter_hooks: ^0.20.0
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  lottie: ^2.5.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  riverpod_annotation: ^2.1.1
  flutter_svg: ^2.0.7
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: FreightSansPro
      fonts:
        - asset: assets/fonts/font/FreightSansProBook-Regular.ttf
        # - asset: assets/fonts/font/FreightSansProBook-Italic.ttf
        #   style: italic
        # - asset: assets/fonts/font/FreightSansProLight-Italic.ttf
        #   style: italic
        #   weight: 300
        - asset: assets/fonts/font/FreightSansProLight-Regular.ttf
          weight: 300
        # - asset: assets/fonts/font/FreightSansProMedium-Italic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/fonts/font/FreightSansProMedium-Regular.ttf
          weight: 600
        # - asset: assets/fonts/font/FreightSansProSemibold-Italic.ttf
        #   weight: 600
        #   style: italic
        - asset: assets/fonts/font/FreightSansProSemibold-Regular.ttf
          weight: 600
        # - asset: assets/fonts/font/FreightSansProBlack-Italic.ttf
        #   style: italic
        #   weight: 900
        - asset: assets/fonts/font/FreightSansProBlack-Regular.ttf
          weight: 900
        - asset: assets/fonts/font/FreightSansProBold-Regular.ttf
          weight: 700

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-black.otf
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanova-bold.otf
          weight: 700
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-extrabold.otf
          weight: 800
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-extraboldit.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-light.otf
          weight: 300
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-lightit.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-medium.otf
          weight: 500
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-mediumit.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-semibold.otf
          weight: 600
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-semiboldit.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-thin.otf
          weight: 200
        - asset: assets/fonts/Demo_Fonts/Fontspring-DEMO-proximanovacond-thinit.otf
          style: italic